docs/docs/building-from-source.md

Seems that libpcap instructions haven't been added yet to the sites wiki, added both for Linux and MacOS as they are just an extra package in their instructions, opted not to add npcap as it is listing in Networking in the wiki

building-from-source.md: Add libpcap instructions to Linux, MacOS

---

docs/docs/building-from-source.md
docs/docs/cli.md

This is the revised and fixed version of Arch Linux build instructions on the wiki. Tested and everything works as it should. (note: also added a link to qemu documentation into this PR)

building-from-source.md: Add Arch Linux Instructions

---

docs/docs/eeprom.md
docs/docs/faq.md
docs/docs/troubleshooting.md

This has came to my attention recently as I've saw an increased amount of people (either privately in DMs or in the Discord) that enable Surround Sound in their eeprom and xemu doesn't work afterwords, adding these warnings/troubleshooting steps is a good idea to try to help mitigate these issues.

Add Surround Sound related questions

---

docs/docs/ftp.md

This aims to add NevoX as a link on the ftp.md page, as over the past few weeks I've saw about 5-8 or so questions asking which dash supports ftp, and adding a FOSS alternative dash that already comes in .iso format further eases the pretty lengthy amount of work you have to do to use this emulator.
Note: This can probably be reworded, I assume you will probably reword this if you find that necessary

ftp.md: Add NevolutionX related link

---

docs/docs/ftp.md

The original xbox (by proxy xemu) has issues with negotiating simultaneous connections via FTP. For example in UnleashX, it adds a "user" everytime a connection is made, and will bug and continue to add users on file transfers. Transferring multiple files also tends to have issues and fail, but transferring the same group of files one at a time doesn't have the same effect and will transfer smoothly.
I have done some thorough testing of transferring files between dashes and this seems to be an issue of most of the alternative dashes that I have tested.

ftp.md: Append Simultaneous Connections to Filezilla instructions

---

docs/docs/building-from-source.md

Git isn't in the dependencies list upon install, some users will likely just copy the list to their clipboard and paste it in the terminal, for linux flavors like debian 11, git doesn't come preinstalled and someone who just picked up linux just to use xemu (which we've observed before) may not know what to do to get it working.

building-from-source.md: Add git to dependencies

---

docs/docs/download.md

I've added the Flatpak installation method to the list.
I've put it on top, because it works on nearly all distributions. Could be moved after the PPA method because of not being as mature, as you wish.
Simplicity-wise, may be harder or easier depending of if the user already has Flatpak locally.

Add Flatpak installation method

---

docs/docs/building-from-source.md

In the xemu discord I suggested adding some instructions on the "Building from Source" page for setting compiler flags when building xemu. Matt asked me to submit a pull request so here it is.
I used `-march=native` as an example flag because that seemed like a relatively harmless example that someone could try and still compile successfully. I tested it myself and ran a few games and it worked well for me. I'm no xemu or C/C++ expert so I'm sorry if this example is more dangerous than it initially seems.

Added instructions for setting C/C++ compiler flags when building xemu

---

docs/docs/disc-images.md

Expands description around the use of xiso to attempt to resolve confusion around xiso versus "normal" ISO.

disc-images.md: Clarified xiso versus .iso

---

docs/docs/building-from-source.md

New build requirement for 0.6.3, mirrors https://github.com/mborgerson/xemu/commit/3be9ea2f92d3f63ecf19b5af457e918a551129ee

Add installation of pyyaml for macOS

---

titles/IL/002/info.json

Changes title from "Braveknight: Leverant Eiyuuden" to "Braveknight: Lieveland Eiyuuden".
リーヴェラント is written as "Lieveland" in official materials, and "Leverant" is not a standard romanization.
http://www.panther.co.jp/brave/index.htm

Change name for Braveknight

---

docs/docs/disc-images.md

`fallocate` can be used to truncate the original file in-place, which is a lot faster than copying using `dd`.
By the way, does anyone know a command to check if a iso is a Redump one?

Add `fallocate` command to truncate the head of Redump ISOs

---

docs/docs/dev/building-from-source.md

This was required to install Xemu on my Arch machine.

Add libslirp to Arch install deps

---

docs/docs/dev/building-from-source.md

This adds a method for using a Steamdeck with steamOS 3.0 to be able to build and develop xemu in the desktop environment.

SteamOS 3 dev Build Environment (via DistroBox)

---

docs/docs/dev/building-from-source.md

This is a needed package that is not in Ubuntu by default, so I have added it to the instructions.

Added libslirp-dev

---

.github/workflows/build.yml
.gitmodules
README.md

Also updates build instructions to indicate that it is required.
An alternative to using a submodule is to have instructions to clone it manually, but I think a submodule is slightly cleaner.

Include xdb as a submodule

---

docs/docs/faq.md

Simple typo fix. Jumped out at me when I looked at the FAQ today.

Fix Insignia typo in FAQ

---

docs/docs/troubleshooting.md

In my previous PR I added `sudo flatpak`:
* https://github.com/xemu-project/xemu-website/pull/157/files#diff-1327bca4414ff874a82cb31aec7614860723b2f79725bfbbfd71b2bf4d54ab67
After some research I found that flatpak overrides are usually documented with the --user flag, likely because not all users have root privileges.
Examples of other emulators who have documented the use of the `--user` flag:
* [Cemu](https://github.com/flathub/info.cemu.Cemu) (Wii U emulator): `flatpak override --user --filesystem=host info.cemu.Cemu`
* [PCSX2](https://github.com/flathub/net.pcsx2.PCSX2): `flatpak override --user net.pcsx2.PCSX2 --filesystem=/path/to/my/PS2_BIOS`
Removed: "Note: Using the same command non-root with the `flatpak --user` parameter will not work."
It didn't work for me before. But when I …

Update troubleshooting.md: Replaced `sudo flatpak override ` with `flatpak override --user`

---

docs/docs/stylesheets/extra.css

AFAICT only affects mobile devices
Before:
After:

extra.css: Update Nav Source Color

---

templates/template_title.html

A couple of changes to address #148:
- wrap text to fit the report box
- highlight field names
Before (desktop)
After (desktop)
Before (mobile)
After (mobile)

Format compatibility reports box to make them easier to read

---

docs/docs/dev/building-from-source.md

Due to the whole venv thing with later revs of Ubuntu, PopOS and Debian, instead of just forcing venv to be disabled, install the venv package, also enforce pip installation due to reliance on tomli, and install python3-tomli, this fixes debian on later releases of python and debian/ubuntu

building-from-source.md: Fix debian dependencies

---

docs/docs/faq.md

Addresses question raised in https://github.com/xemu-project/xemu/issues/1862

Add note on portable mode for macOS

---

docs/docs/dev/building-from-source.md

I'm unable to build on Arch via the current install instructions. Upon installing the cmake and vulkan-headers packages, I was able to build from source easily. This PR adds those packages to the instructions.

Fix arch install instructions by including missing packages

---

generate.py

Grab the state_reason using the API and only allow issues to qualify as recently closed if the state_reason is completed (and not anything else like invalid or duplicate). Tested by building the website locally with the changes: the fix appears to work fine with no issues. It accurately removes known duplicate/invalid issues while keeping valid completed ones.
(Also on line 247, you possibly could remove `i.state != open` since theoretically an issue probably cannot have `i.state_reason == 'completed'`  if it is open. So we can change if you want.)
Closes https://github.com/xemu-project/xemu-website/issues/214

Recently Closed Issues: Filter out invalid/duplicate issues by only allowing 'completed' issues
