docs/docs/building-from-source.md
Reverts mborgerson/xemu-website#35
Deps and formatting issues.
=> Revert "Add Arch Linux Build Instructions"

docs/docs/faq.md
Caught by Xbox7887, fixes broken redump question link
=> faq.md: fix broken faq link

docs/docs/building-from-source.md
Tested this on a fresh fedora 35 install and it worked just fine
=> added commands to install dependencies on fedora

docs/docs/download.md
Oops it is `app.xemu.xemu`, not `org.xemu.xemu`, sorry.
=> Fix app.xemu.xemu name

templates/template_base.html
Reverts mborgerson/xemu-website#57
=> Revert "template_base.html: Update jquery, popper, and bootstrap"

templates/template_base.html
=> template_base.html: Update Copyright Year

docs/docs/building-from-source.md
Tested on Windows and Arch Linux. Should be safe to assume it'll work on the other platforms.
=> Update build instructions for v0.6.3

docs/docs/faq.md
Let me know if anything is incorrect or if I missed an important point.
=> Add faq note on Vulkan support

docs/docs/dev/building-from-source.md
Attempting to cover the most common issues raised on Discord.
=> Add some tips to the Windows build section

docs/docs/dev/debug/graphics.md, docs/docs/dev/debug/guest.md, docs/docs/dev/debug/host.md, docs/docs/dev/debug/index.md, docs/mkdocs.yml
This should serve as a good starting point for some developer documentation. There's lots more to do, and I'm still debating how much depth to cover, but definitely open to any early feedback. This will likely remain in draft status for a bit as I continue to flush things out, particularly the graphics section, which I'll probably yield to others.
=> Add debug docs

docs/docs/required-files.md, docs/docs/xmus.md
[FATXplorer added support for creating/formatting a file last year](https://fatxplorer.eaton-works.com/2021/08/18/fatxplorer-3-0-beta-15--formatting-a-file-is-now-supported/). It can create both original Xbox HDD and MU images. This may make it easier for your users, so I've proposed a few docs updates through this PR.
=> Add FATXplorer mention to docs

docs/docs/required-files.md
Clarified previously unmentioned issues with using an unmodified retail BIOS.
=> Updated "Required files" doc

generate.py, templates/top_issues.html
=> List top blocking issues

docs/docs/dev/building-from-source.md
I had a spelling error when I did my pr last time and didn’t notice it and this should fix the error. gile -> file
=> Fix Spelling in steamOS instructions

docs/mkdocs.yml, templates/template_base.html
Straight forward change, just updated to 2024
=> Update to Copyright Year

docs/docs/download.md, docs/docs/troubleshooting.md
Reference: "I'll close this issue and ask that you instead send a PR with your proposed changes." - [mborgerson](https://github.com/xemu-project/xemu-website/issues/156#issuecomment-2468966810)
=> Update download.md and troubleshooting.md: Add `flatpak override` to access xbox_hdd.qcow2 in custom directories

docs/mkdocs.yml, templates/template_base.html
=> Base Template and Mkdocs: Update Copyright Year

docs/docs/dev/debug/graphics.md
I see that you have the guide as a wip, it's a good idea to expose these other tools at least for now till a more formal guide is written for them
=> graphics.md: Add other tools into tip

docs/docs/dev/index.md
Some initial notes on patch submission process. Could use more refining, but this works for now.
=> dev: Add patch submission guidelines

docs/docs/troubleshooting.md
=> Add link to LithiumX for cache clearing

README.md
=> Add Arch Linux build instructions
